$(document).ready(function () {
    var resourceUrl = 'https://baas.kinvey.com/appdata/kid_byeNbqtPyW/persons';

    $.ajaxSetup({
        headers: {
            'Authorization': 'Basic cGVzaG86MTIzNDU=', // Generated by username = 'pesho', password = '12345'
            'Content-Type': 'application/json'
        }
    });

    $.ajax({
        url: resourceUrl,
        method: 'GET',
        contentType: 'application/json',
        success: function (data) {
            var personsObj = {
                "items": []
            };
            data.forEach(function(person) {
                personsObj.items.push({
                    "name": person.name,
                    "job": person.job,
                    "website": person.website
                })
            });

            $.get('templates/persons.html', function (persons) {
                var output = Mustache.render(persons, personsObj);
                $('#wrapper').html(output);
            });
        },
        error: function (err) {
            console.log(err);
        }
    });
});