$(document).ready(function () {
    var resourceUrl = 'https://baas.kinvey.com/appdata/kid_byeNbqtPyW/students';

    $.ajaxSetup({
        headers: {
            'Authorization': 'Basic cGVzaG86MTIzNDU=', // Generated by username = 'pesho', password = '12345'
            'Content-Type': 'application/json'
        }
    });

    $.ajax({
        url: resourceUrl,
        method: 'GET',
        contentType: 'application/json',
        success: function (data) {
            var studentsObj = {
                "students": []
            };
            data.forEach(function(student) {
                studentsObj.students.push({
                    "fullName": student.firstName + ' ' + student.lastName,
                    "age": student.age,
                    "country": student.country
                })
            });

            $.get('templates/students.html', function (students) {
                var output = Mustache.render(students, studentsObj);
                $('#wrapper').html(output);
            });
        },
        error: function (err) {
            console.log(err);
        }
    });
});